Initial version
opeepl/chartjs-plugin-imagelabels pull request #1
Opened 2023-02-23 18:27 UTC by Voodu

Create basic plugin structure with linter, tests etc.

2023-02-24 10:33 UTC, MariusOpeepl requested changes

2023-02-24 10:33 UTC, MariusOpeepl commented on src/__tests__/geometry-utils.test.ts
> +        const oldRect = { width: 10, height: 20 };
This isn't doing any actual resizing, since the largest side of the rectangle is already at newSize, you should give newSize a value higher than 20.

2023-02-24 10:33 UTC, MariusOpeepl commented on src/__tests__/geometry-utils.test.ts
> +describe('GeometryUtils.resizeRect', () => {
You could do with two extra things:
- besides growing, also test shrinking of squares and rectangles, e.g. a square with a side of 10px to a newSize of 5.
- test a rectangle with `width > height`, both growing and shrinking

With 3 types of rects and 2 types of resizing you're at 6 test cases, it might be worthwhile to use data providers. There are some Jest `.test.ts` files in our main repo that do that, but it's up to you if you think it's worth using providers.

2023-02-24 10:33 UTC, MariusOpeepl commented on src/defaults.ts
> +// This is the standard image-off.svg, but with a couple extra attributes:
Being a public repo, others may not understand what the standard `image-off.svg` is. You could either remove that part of the description, or the entire description, since it's not really tied to our system anymore.

2023-02-24 10:33 UTC, MariusOpeepl commented on src/geometry-utils.ts
> +     */
Remember to update the comments & parameter names in our opeepl-dist too

2023-02-27 08:18 UTC, Voodu commented on src/__tests__/geometry-utils.test.ts
> +describe('GeometryUtils.resizeRect', () => {
Goal of this commit is just to provide some example of the project structure, so those tests are also more like PoC. I added a bit more to make it complete, but adding data providers seems like an overkill in this case.

2023-02-27 08:19 UTC, Voodu commented on src/geometry-utils.ts
> +     */
I just removed them from there. We can import them from here if we need to

2023-02-27 08:21 UTC, MariusOpeepl commented on src/geometry-utils.ts
> +     */
Yeah, that would work. I thought the opeepl-dist variant was going to stay.

2023-02-27 08:21 UTC, Voodu commented on src/geometry-utils.ts
> +     */
It has to be this one, as we can't use opeepl-dist code in here

2023-02-27 08:23 UTC, MariusOpeepl commented on src/geometry-utils.ts
> +     */
I'm not sure how I feel about exposing the utility classes of a ChartJS plugin, but I don't have a better solution for this.

2023-02-27 08:25 UTC, MariusOpeepl approved these changes

2023-02-27 08:26 UTC, merged